### ISSUE TITLE
STCommon.h:99:46: error: left operand of shift expression

### ISSUE THREAD

**Issue by noregrof** [walaj/svaba#14]
Trying to compile with GCC  version gcc (GCC) 6.1.0 

I got 

`../../../src/SGA/SuffixTools/STCommon.h:99:49: warning: left shift of negative value [-Wshift-negative-value]
         static const uint64_t HIGH_MASK = ~0 << POS_BITS;
                                                 ^~~~~~~~
../../../src/SGA/SuffixTools/STCommon.h:99:46: error: left operand of shift expression '(-1 << 28)' is negative [-fpermissive]
         static const uint64_t HIGH_MASK = ~0 << POS_BITS;
`

I changed the line to 

`static const uint64_t HIGH_MASK = (~((uint64_t)(0))) << POS_BITS;`

It solved the compilation probleme.

**Comment by walaj** [comment]
Thank you for the fix. I made the update. Let me know if further issues, but I'll close this thread.
